/**
 * Concept questions, the "explain X" half of an interview loop.
 * Each answer is sized for 30 to 60 seconds of talking.
 *
 * Generated by scripts/build-concepts.py. Edit the source, not this file.
 */

export type Concept = { id: string; question: string; answer: string }
export type ConceptGroup = { id: string; name: string; concepts: Concept[] }

export const conceptGroups: ConceptGroup[] = [
  {
    id: 'oop',
    name: "OOP",
    concepts: [
      {
        id: 'what-is-oop',
        question: "What is OOP?",
        answer: "Object-oriented programming organizes code around objects, which bundle data\n(state) with the functions that work on it (methods). Instead of passing data\naround to loose functions, you model things in your domain, like a User or a\nShoppingCart, as objects that manage their own state and expose a small public\ninterface. It's usually described through four principles: encapsulation,\nabstraction, inheritance and polymorphism.\n\nExpect the follow-up \"explain the four pillars\" or \"is JavaScript OOP?\".",
      },
      {
        id: 'the-four-pillars',
        question: "The four pillars",
        answer: "Encapsulation: an object hides its internal state and only lets it change\nthrough its methods. A BankAccount exposes deposit() and withdraw(), not a\nwritable balance field, so it can enforce \"no negative balance\".\n\nAbstraction: expose what something does, hide how. You call cart.total()\nwithout knowing about the tax rules and discounts inside.\n\nInheritance: a class extends another and reuses its behavior. AdminUser\nextends User and adds permissions.\n\nPolymorphism: different types used through the same interface, each\nresponding its own way. Circle and Square both have area(), and code looping\nover shapes calls shape.area() without caring which one it has.",
      },
      {
        id: 'class-vs-object',
        question: "Class vs object",
        answer: "A class is the blueprint, an object is an instance built from it.\n`class User {}` is defined once, `new User(\"anna\")` and `new User(\"nikos\")`\nare two objects with their own state.",
      },
      {
        id: 'composition-vs-inheritance',
        question: "Composition vs inheritance",
        answer: "Inheritance is \"is-a\" (Admin is a User), composition is \"has-a\" (Car has an\nEngine). The usual advice is to favor composition, because deep inheritance\ntrees get rigid: a change in the base class ripples into every child, and you\ncan't mix behavior from two parents. React is a good example. It doesn't use\ncomponent inheritance at all, you compose components and share logic with\nhooks.",
      },
      {
        id: 'interface-vs-abstract-class',
        question: "Interface vs abstract class",
        answer: "An interface is only a contract: method signatures, no implementation. An\nabstract class can include implemented methods and state, but can't be\ninstantiated directly. A class can implement many interfaces but extend only\none class. In TypeScript, interfaces disappear at compile time, abstract\nclasses exist at runtime.",
      },
      {
        id: 'overloading-vs-overriding',
        question: "Overloading vs overriding",
        answer: "Overriding: a subclass replaces a method it inherited, same name and\nsignature. Overloading: several methods with the same name but different\nparameters. JavaScript has no real overloading. TypeScript lets you declare\noverload signatures, but there's still one implementation that checks its\narguments.",
      },
      {
        id: 'is-javascript-object-oriented',
        question: "Is JavaScript object-oriented?",
        answer: "Yes, but prototype-based rather than class-based. Objects inherit directly\nfrom other objects through the prototype chain, and the ES6 `class` keyword is\nmostly syntax over that. JS is multi-paradigm, you can write it OOP style or\nfunctional style, and modern React leans functional.",
      },
      {
        id: 'solid',
        question: "SOLID",
        answer: "S, single responsibility: a class or module has one reason to change. A\ncomponent that fetches data, formats it and renders it is doing three jobs.\n\nO, open/closed: open for extension, closed for modification. Add behavior by\nadding code (a new variant, a new strategy) instead of editing a growing\nswitch statement.\n\nL, Liskov substitution: a subclass should work anywhere its parent works\nwithout surprising the caller. The classic violation is Square extends\nRectangle, where setting the width silently changes the height.\n\nI, interface segregation: several small interfaces beat one big one, so\nnobody depends on methods they don't use. In React terms, don't hand a giant\nprops object to a component that reads two fields.\n\nD, dependency inversion: depend on abstractions, not concrete\nimplementations. Your checkout depends on a PaymentProvider interface and\nStripe is one implementation you pass in, which also makes it easy to mock in\ntests.",
      },
      {
        id: 'static-members',
        question: "Static members",
        answer: "They belong to the class, not to instances. `Math.max()` is static, you never\nwrite `new Math()`. Use them for utilities and factory methods that don't need\ninstance state.",
      },
      {
        id: 'access-modifiers',
        question: "Access modifiers",
        answer: "public, private and protected control who can touch a member. TypeScript's\n`private` is only checked at compile time. JavaScript's `#field` is private at\nruntime.",
      },
    ],
  },
  {
    id: 'functional-programming',
    name: "Functional programming",
    concepts: [
      {
        id: 'what-is-functional-programming',
        question: "What is functional programming?",
        answer: "Building programs from pure functions and avoiding shared mutable state. Data\ngoes in, new data comes out, nothing changes in place. map, filter and reduce\nare the everyday version.",
      },
      {
        id: 'pure-function',
        question: "Pure function",
        answer: "Same input always gives the same output, and no side effects: no network, no\nDOM, no mutating arguments. Easy to test and reason about. React expects\nrendering to be pure, which is why side effects go in useEffect or event\nhandlers.",
      },
      {
        id: 'immutability',
        question: "Immutability",
        answer: "Never change existing data, create a copy with the change. In React this\nmatters because updates are detected by reference: if you push into the\nexisting array, the reference doesn't change and React can skip the\nre-render. So you write `setItems([...items, newItem])`.",
      },
      {
        id: 'higher-order-functions-and-currying',
        question: "Higher-order functions and currying",
        answer: "A higher-order function takes or returns a function: map, a debounce wrapper,\na HOC. Currying turns f(a, b) into f(a)(b), handy for partial application:\n`const onChange = field => e => setForm({ ...form, [field]: e.target.value })`.",
      },
      {
        id: 'oop-vs-fp',
        question: "OOP vs FP",
        answer: "OOP groups data and behavior together and manages change through an object's\ninternal state. FP keeps data and functions apart and avoids mutation. OOP\nfits entities with a lifecycle, FP fits data transformations and is easier to\ntest. Real codebases mix them: a React app is mostly functional components,\nwith classes here and there for API clients or custom errors.",
      },
    ],
  },
  {
    id: 'javascript-and-typescript',
    name: "JavaScript and TypeScript",
    concepts: [
      {
        id: 'var-vs-let-vs-const',
        question: "var vs let vs const",
        answer: "var is function-scoped and hoisted as undefined, which causes bugs like the\nclassic closure-in-a-loop problem. let and const are block-scoped. const stops\nyou reassigning the variable, but an object held by a const can still be\nmutated.",
      },
      {
        id: 'hoisting',
        question: "Hoisting",
        answer: "Declarations are processed before the code runs. Function declarations are\nfully hoisted, so you can call them above where they're written. var is\nhoisted as undefined. let and const are hoisted too, but accessing them before\nthe declaration throws (the \"temporal dead zone\").",
      },
      {
        id: 'closures',
        question: "Closures",
        answer: "A function remembers the variables of the scope it was created in, even after\nthat scope has finished. Example: a counter factory returns a function that\nincrements a private count. In React the common bug is a stale closure, like a\nsetInterval inside useEffect that keeps seeing the state from the first\nrender.",
      },
      {
        id: 'how-does-this-work',
        question: "How does `this` work?",
        answer: "It depends on how the function is called, not where it's defined. obj.method()\ngives obj. A plain call gives undefined in strict mode. With new, it's the new\nobject. call, apply and bind set it explicitly. Arrow functions don't have\ntheir own this, they take it from the surrounding scope.",
      },
      {
        id: 'event-loop',
        question: "Event loop",
        answer: "JS runs on one thread with a call stack. Async work (timers, network) is\nhandled by the browser or Node, and when it's done its callback gets queued.\nWhen the stack is empty the event loop picks up the next task. Microtasks\n(promise callbacks) are all drained after each task, before the next\nmacrotask (setTimeout, events). So this logs 2, then 1:\n\n```js\nsetTimeout(() => console.log(1));\nPromise.resolve().then(() => console.log(2));\n```",
      },
      {
        id: 'promises-vs-async-await',
        question: "Promises vs async/await",
        answer: "Same mechanism. A promise is a future value that's pending, fulfilled or\nrejected. async/await is syntax on top that reads top to bottom and works\nwith try/catch. Know the combinators: Promise.all rejects as soon as one\nrejects, allSettled waits for all of them, race takes the first to settle,\nany takes the first to fulfill.",
      },
      {
        id: 'equality-vs-strict-equality',
        question: "== vs ===",
        answer: "=== compares value and type with no conversion. == converts types first, so\n`0 == \"\"` and `null == undefined` are both true. Use === by default.\n`x == null` is the one common intentional use, it checks for null and\nundefined at once.",
      },
      {
        id: 'null-vs-undefined',
        question: "null vs undefined",
        answer: "undefined means nothing was assigned: missing property, missing argument.\nnull is an intentional \"no value\" set by the programmer. `typeof null` is\n\"object\", a bug kept for backwards compatibility.",
      },
      {
        id: 'prototypal-inheritance',
        question: "Prototypal inheritance",
        answer: "Every object has a hidden link to a prototype. When a property isn't on the\nobject, JS walks up the chain until it finds it or reaches null. That's how an\narray has map: it lives on Array.prototype.",
      },
      {
        id: 'shallow-vs-deep-copy',
        question: "Shallow vs deep copy",
        answer: "A shallow copy (spread, Object.assign) copies the top level, nested objects\nare still shared. A deep copy duplicates everything, use structuredClone().\nJSON.parse(JSON.stringify(x)) works but loses dates, functions and undefined.",
      },
      {
        id: 'debounce-vs-throttle',
        question: "Debounce vs throttle",
        answer: "Debounce waits until calls stop for N ms, then runs once: a search box that\nfires after typing stops. Throttle runs at most once every N ms while calls\nkeep coming: scroll and resize handlers. Be ready to write debounce live:\n\n```js\nfunction debounce(fn, ms) {\n  let t;\n  return (...args) => {\n    clearTimeout(t);\n    t = setTimeout(() => fn(...args), ms);\n  };\n}\n```",
      },
      {
        id: 'bubbling-capturing-delegation',
        question: "Bubbling, capturing, delegation",
        answer: "Events travel from the window down to the target (capture), then back up\n(bubble). Most listeners run on the way up. Delegation uses that: one\nlistener on the parent list instead of one per item, then check event.target.\nstopPropagation stops the travel, preventDefault stops the browser's default\naction, like a form submit. They're different things.",
      },
      {
        id: 'typescript-interface-vs-type',
        question: "TypeScript: interface vs type",
        answer: "Both describe object shapes and mostly overlap. Interfaces can be extended and\nmerged by redeclaring them. Types can also express unions, intersections,\nmapped and conditional types. A common convention is interface for object\nshapes and public APIs, type for the rest. Consistency matters more than the\nchoice.",
      },
      {
        id: 'any-vs-unknown-vs-never',
        question: "any vs unknown vs never",
        answer: "any turns type checking off. unknown holds anything but forces you to narrow\nbefore use, which makes it the right type for API responses and caught\nerrors. never is a value that can't exist, used for exhaustive switch checks.",
      },
      {
        id: 'generics',
        question: "Generics",
        answer: "Type parameters, so one function or component works with many types and\nstays type safe: `function first<T>(arr: T[]): T | undefined`. In React, a\n`List<T>` component whose renderItem receives the correct item type.",
      },
    ],
  },
  {
    id: 'react',
    name: "React",
    concepts: [
      {
        id: 'virtual-dom-and-reconciliation',
        question: "Virtual DOM and reconciliation",
        answer: "React keeps a lightweight tree describing the UI. Each render produces a new\ntree, React diffs it against the previous one and applies the smallest set of\nreal DOM changes. The diff uses shortcuts: a different element type replaces\nthe whole subtree, and keys identify list items. The point isn't that it beats\nthe real DOM on speed, it's that you write declarative UI and React handles\nand batches the updates.",
      },
      {
        id: 'why-do-keys-matter',
        question: "Why do keys matter?",
        answer: "Keys tell React which list item is which across renders. With stable ids it\nupdates or moves the right elements. With index keys, inserting or reordering\ncan attach state to the wrong item, like an input's text jumping to another\nrow.",
      },
      {
        id: 'state-vs-props',
        question: "State vs props",
        answer: "Props come from the parent and are read-only for the child. State is owned by\nthe component and changes through its setter. A change in either triggers a\nre-render.",
      },
      {
        id: 'when-does-a-component-re-render',
        question: "When does a component re-render?",
        answer: "When its state changes, when its parent re-renders (even if props are the\nsame), or when a context it reads changes. React.memo skips the render if\nprops are shallow-equal.",
      },
      {
        id: 'useeffect',
        question: "useEffect",
        answer: "Runs side effects after render: fetching, subscriptions, syncing with things\noutside React. No dependency array means every render, `[]` means once after\nmount, `[a, b]` means when those change. The cleanup function runs before the\nnext effect and on unmount, for unsubscribing or aborting a fetch. Common\nmistake: using an effect to compute state you could derive during render.",
      },
      {
        id: 'usememo-usecallback-react-memo',
        question: "useMemo, useCallback, React.memo",
        answer: "useMemo caches a computed value, useCallback caches a function reference,\nReact.memo skips re-rendering a component whose props didn't change. They\nwork together: memo on a child does nothing if the parent passes a new\nfunction or object every render. Measure before wrapping everything. The\nReact Compiler now does most of this automatically.",
      },
      {
        id: 'controlled-vs-uncontrolled-inputs',
        question: "Controlled vs uncontrolled inputs",
        answer: "Controlled: React state holds the value and updates on every keystroke, so\nReact is the source of truth. Uncontrolled: the DOM holds the value and you\nread it with a ref or FormData on submit. Controlled is easier for validation\nand dependent fields, uncontrolled is simpler and renders less on big forms.",
      },
      {
        id: 'context-vs-a-state-library',
        question: "Context vs a state library",
        answer: "Context passes values down without prop drilling and suits things that change\nrarely: theme, current user, locale. Every consumer re-renders when the value\nchanges, so it's a poor fit for fast-changing global state. Zustand, Redux or\nJotai let components subscribe to slices. Server data belongs in TanStack\nQuery or similar, not global state.",
      },
      {
        id: 'are-state-updates-synchronous',
        question: "Are state updates synchronous?",
        answer: "No. setState schedules an update, and React batches updates from the same\nevent into one render. Reading state right after setting it gives the old\nvalue. If the next value depends on the previous one, use the updater form:\n`setCount(c => c + 1)`.",
      },
      {
        id: 'custom-hooks-and-rules-of-hooks',
        question: "Custom hooks and rules of hooks",
        answer: "A custom hook is a function starting with use that calls other hooks, for\nsharing stateful logic (useDebounce, useFetch). Each component using it gets\nits own state: hooks share logic, not state. Rules: call hooks only at the top\nlevel, never in conditions or loops, and only from components or hooks.\nReact matches state to hooks by call order, so a changing order breaks it.",
      },
      {
        id: 'csr-vs-ssr-vs-ssg-and-hydration',
        question: "CSR vs SSR vs SSG, and hydration",
        answer: "CSR: the server sends an empty shell and JS renders everything in the\nbrowser. Easy hosting, slower first paint, weaker SEO. SSR: the server renders\nHTML per request so content shows fast, then hydration attaches React's event\nhandlers to that HTML. SSG: HTML generated at build time, fastest, but only as\nfresh as the last build. Next.js lets you choose per route.",
      },
      {
        id: 'server-components',
        question: "Server Components",
        answer: "Components that run only on the server and send rendered output instead of\nJS. They can query the database directly and add nothing to the bundle. They\ncan't use state, effects or browser APIs, anything interactive needs a\n\"use client\" component.",
      },
      {
        id: 'error-boundaries',
        question: "Error boundaries",
        answer: "Components that catch render errors in their subtree and show a fallback\ninstead of unmounting the whole app. Still written as class components or via\nreact-error-boundary. They don't catch errors in event handlers or async code.",
      },
    ],
  },
  {
    id: 'web-and-browser',
    name: "Web and browser",
    concepts: [
      {
        id: 'what-happens-when-you-type-a-url-and-press-enter',
        question: "What happens when you type a URL and press Enter?",
        answer: "DNS resolves the domain to an IP, checking caches first. The browser opens a\nTCP connection plus a TLS handshake for HTTPS and sends the HTTP request. The\nserver returns HTML. The browser parses it into the DOM and the CSS into the\nCSSOM, combines them into a render tree, calculates layout, paints and\ncomposites. Scripts and assets load along the way, and a plain script tag\nblocks parsing unless it's defer or async. Go as deep as the interviewer\nseems to want.",
      },
      {
        id: 'http-methods-and-idempotency',
        question: "HTTP methods and idempotency",
        answer: "GET reads, POST creates, PUT replaces, PATCH updates part of a resource,\nDELETE removes. Idempotent means doing it twice has the same effect as once.\nGET, PUT and DELETE are, POST isn't, which matters when you retry requests.",
      },
      {
        id: 'status-codes',
        question: "Status codes",
        answer: "2xx success: 200, 201 Created, 204 No Content. 3xx redirects: 301 permanent,\n302 temporary, 304 Not Modified. 4xx client errors: 400, 401 not\nauthenticated, 403 authenticated but not allowed, 404, 429 too many requests.\n5xx server errors: 500, 502 bad gateway, 503 unavailable. 401 vs 403 is a\nfavorite.",
      },
      {
        id: 'rest-vs-graphql',
        question: "REST vs GraphQL",
        answer: "REST exposes resources at URLs with HTTP methods. Simple and HTTP-cacheable,\nbut screens can over-fetch or need several round trips. GraphQL has one\nendpoint where the client asks for exactly the fields it needs, which suits\ncomplex UIs and many client types, but caching is harder and clients can send\nexpensive queries.",
      },
      {
        id: 'cookies-vs-localstorage-vs-sessionstorage',
        question: "Cookies vs localStorage vs sessionStorage",
        answer: "Cookies go with every request to their domain, hold about 4KB, and can be\nhttpOnly (unreadable by JS) and secure, which makes them the right place for\nauth. localStorage holds about 5MB, stays until cleared, and is never sent to\nthe server. sessionStorage is the same but per tab and gone when the tab\ncloses. Tokens in localStorage can be stolen by any XSS.",
      },
      {
        id: 'cors',
        question: "CORS",
        answer: "The browser blocks JS from reading responses from another origin (scheme,\ndomain or port) unless the server allows it with headers like\nAccess-Control-Allow-Origin. Non-simple requests get a preflight OPTIONS\nrequest first. The browser enforces it, so CORS doesn't protect an API from\ncurl or another server.",
      },
      {
        id: 'xss-and-csrf',
        question: "XSS and CSRF",
        answer: "XSS: an attacker gets script running on your page, usually through unescaped\nuser input. React escapes output by default, dangerouslySetInnerHTML is the\ngap. Defenses: escaping, sanitizing, a Content Security Policy, httpOnly\ncookies. CSRF: another site makes the user's browser send an authenticated\nrequest to yours using their cookies. Defenses: SameSite cookies and CSRF\ntokens.",
      },
      {
        id: 'authentication-vs-authorization-sessions-vs-jwt',
        question: "Authentication vs authorization, sessions vs JWT",
        answer: "Authentication is who you are, authorization is what you're allowed to do.\nSessions keep state on the server and give the client an id in a cookie, easy\nto revoke. A JWT is a signed token carrying the claims itself, stateless and\neasy to scale, but hard to revoke before it expires, so it's usually\nshort-lived and paired with a refresh token.",
      },
      {
        id: 'reflow-vs-repaint',
        question: "Reflow vs repaint",
        answer: "Reflow (layout) recalculates sizes and positions: changing width, adding\nnodes, or reading offsetHeight right after a write. Repaint redraws pixels\nwithout layout, like a color change. Reflow costs more. transform and opacity\ncan skip both and run on the compositor, which is why you animate those.",
      },
      {
        id: 'core-web-vitals',
        question: "Core Web Vitals",
        answer: "LCP, largest contentful paint, measures loading: under 2.5s. INP, interaction\nto next paint, measures responsiveness: under 200ms. CLS, cumulative layout\nshift, measures visual stability: under 0.1. Typical fixes: optimized and\npreloaded images, code splitting, less JS on the main thread, reserved space\nfor images.",
      },
      {
        id: 'http-caching',
        question: "HTTP caching",
        answer: "Cache-Control says how long to keep a response: max-age, no-cache (store but\nrevalidate), no-store (never store). ETag and Last-Modified let the browser\nask whether something changed and get a cheap 304. Common setup: hashed\nstatic assets cached for a year, HTML revalidated on every load.",
      },
      {
        id: 'polling-vs-sse-vs-websockets',
        question: "Polling vs SSE vs WebSockets",
        answer: "Polling: the client asks repeatedly, simple but wasteful. Long polling: the\nserver holds the request open until there's data. SSE: one-way server push\nover HTTP, fine for notifications, live feeds and streaming AI responses.\nWebSockets: persistent two-way connection, for chat, multiplayer and\ncollaborative editing.",
      },
      {
        id: 'http-2-and-http-3',
        question: "HTTP/2 and HTTP/3",
        answer: "HTTP/2 multiplexes many requests over one connection and compresses headers,\nso bundling everything into one file matters less. HTTP/3 runs on QUIC over\nUDP, which removes TCP's head-of-line blocking and survives network switches\nbetter on mobile.",
      },
      {
        id: 'accessibility-basics',
        question: "Accessibility basics",
        answer: "Semantic HTML first (a button, not a clickable div), labeled inputs, alt text,\nfull keyboard navigation with visible focus, enough contrast. ARIA only when\nHTML can't express it. A common question is making a custom modal accessible:\ntrap focus inside, close on Escape, return focus to the trigger on close, set\nrole=\"dialog\".",
      },
    ],
  },
  {
    id: 'cs-fundamentals',
    name: "CS fundamentals",
    concepts: [
      {
        id: 'big-o',
        question: "Big O",
        answer: "How time or memory grows with input size, ignoring constants. O(1) hash\nlookup, O(log n) binary search, O(n) a single loop, O(n log n) a good sort,\nO(n^2) nested loops. State both time and space when you present a solution.",
      },
      {
        id: 'array-vs-linked-list',
        question: "Array vs linked list",
        answer: "Arrays are contiguous memory: O(1) access by index, O(n) insert in the middle\nbecause elements shift. Linked lists insert and delete in O(1) if you already\nhold the node, but finding anything is O(n) and cache locality is worse. In\npractice arrays win most of the time.",
      },
      {
        id: 'how-does-a-hash-map-work',
        question: "How does a hash map work?",
        answer: "A hash function turns the key into an index in an array of buckets, giving\nO(1) average lookup, insert and delete. Collisions are handled by chaining or\nprobing, and the table resizes when it gets too full. Worst case is O(n). In\nJS, Map keeps insertion order, accepts any key type and has size, a plain\nobject only takes string or symbol keys.",
      },
      {
        id: 'stack-vs-queue',
        question: "Stack vs queue",
        answer: "Stack is last in, first out: the call stack, undo, DFS, bracket matching.\nQueue is first in, first out: BFS, job processing, the event loop's task\nqueue.",
      },
      {
        id: 'trees-graphs-bfs-vs-dfs',
        question: "Trees, graphs, BFS vs DFS",
        answer: "A tree is a connected graph with no cycles and a single root, the DOM is one.\nBFS explores level by level with a queue and finds shortest paths in\nunweighted graphs. DFS goes deep first with recursion or a stack, good for\nexhaustive search, cycle detection and topological sort.",
      },
      {
        id: 'recursion',
        question: "Recursion",
        answer: "A function calls itself on a smaller version of the problem, with a base case\nthat stops it. Every call takes stack space, so deep recursion can overflow,\nand any recursion can be rewritten with an explicit stack.",
      },
      {
        id: 'process-vs-thread',
        question: "Process vs thread",
        answer: "A process is a running program with its own memory. Threads live inside a\nprocess and share its memory, cheaper to create but needing synchronization.\nWeb Workers give the browser extra threads that communicate by messages\ninstead of shared memory. Node runs your JS on one thread and uses a thread\npool for some I/O.",
      },
      {
        id: 'concurrency-vs-parallelism',
        question: "Concurrency vs parallelism",
        answer: "Concurrency is handling many things by interleaving them, like the event loop\nserving many requests on one thread. Parallelism is running things at the\nsame instant on multiple cores.",
      },
      {
        id: 'race-conditions-and-deadlocks',
        question: "Race conditions and deadlocks",
        answer: "A race condition is when the result depends on timing. React example: two\nsearch requests return out of order and the older result overwrites the\nnewer, fixed with AbortController or by ignoring stale responses. A deadlock\nis two processes each waiting on a lock the other holds, so neither moves.",
      },
    ],
  },
  {
    id: 'databases',
    name: "Databases",
    concepts: [
      {
        id: 'sql-vs-nosql',
        question: "SQL vs NoSQL",
        answer: "SQL databases (Postgres, MySQL) have schemas, related tables, joins and\nstrong transactions. Good when data is relational and consistency matters,\nlike payments. NoSQL covers document (MongoDB), key-value (Redis),\nwide-column (Cassandra) and graph stores: flexible schemas and usually easier\nhorizontal scaling, weaker joins and often weaker consistency. For a typical\napp the default is Postgres unless there's a specific reason not to.",
      },
      {
        id: 'indexes',
        question: "Indexes",
        answer: "A structure, usually a B-tree, that finds rows without scanning the whole\ntable, like the index at the back of a book. Reads on indexed columns get\nfaster, writes get slower and storage grows because the index must be kept\nup to date. Index the columns you filter, join and sort on.",
      },
      {
        id: 'acid',
        question: "ACID",
        answer: "Atomicity: a transaction happens fully or not at all. Consistency:\nconstraints hold before and after. Isolation: concurrent transactions don't\nsee each other's half-finished work. Durability: once committed, it survives\na crash. The standard example is a bank transfer that debits one account and\ncredits another.",
      },
      {
        id: 'normalization-vs-denormalization',
        question: "Normalization vs denormalization",
        answer: "Normalization stores each fact once across related tables, avoiding\ninconsistent updates. Denormalization duplicates data on purpose to skip\nexpensive joins on read-heavy paths. Normalize by default, denormalize where\nyou've measured a read problem.",
      },
      {
        id: 'joins',
        question: "Joins",
        answer: "INNER returns rows that match in both tables. LEFT returns every row from the\nleft table plus matches, with nulls where there's none. RIGHT is the reverse,\nFULL returns everything from both.",
      },
      {
        id: 'the-n-1-query-problem',
        question: "The N+1 query problem",
        answer: "One query fetches a list, then one more query per item fetches related data:\n100 posts become 101 queries. Fix it with a join, a single batched IN query,\nor eager loading in the ORM. In GraphQL the usual fix is DataLoader.",
      },
    ],
  },
  {
    id: 'system-design-concepts',
    name: "System design concepts",
    concepts: [
      {
        id: 'vertical-vs-horizontal-scaling',
        question: "Vertical vs horizontal scaling",
        answer: "Vertical means a bigger machine: simple, but it has a ceiling and stays a\nsingle point of failure. Horizontal means more machines behind a load\nbalancer: scales further, but servers need to be stateless and you inherit\ndistributed-system problems.",
      },
      {
        id: 'load-balancer',
        question: "Load balancer",
        answer: "Spreads requests across servers (round robin, least connections, hashing)\nand stops routing to unhealthy ones. It's what makes horizontal scaling and\nzero-downtime deploys possible.",
      },
      {
        id: 'caching-and-invalidation',
        question: "Caching and invalidation",
        answer: "Keep results of expensive work closer to where they're needed: browser, CDN,\napp memory, Redis. Cache-aside is the common pattern: check the cache, on a\nmiss load from the database and store it. Entries expire by TTL or get\ninvalidated on writes. Invalidation is the hard part, stale data is the usual\nbug.",
      },
      {
        id: 'cdn',
        question: "CDN",
        answer: "Geographically spread servers that cache static content (images, JS, CSS,\nsometimes whole pages) near users. Lower latency for them, less load on your\norigin.",
      },
      {
        id: 'cap-theorem',
        question: "CAP theorem",
        answer: "When a distributed system hits a network partition, it has to choose between\nconsistency (every node returns the same data) and availability (every\nrequest gets a response). Payments choose consistency, social feeds usually\nchoose availability and accept eventual consistency.",
      },
      {
        id: 'monolith-vs-microservices',
        question: "Monolith vs microservices",
        answer: "A monolith is one deployable app, simple to build, test and deploy early on.\nMicroservices split it into independently deployable services, often owned by\nseparate teams, which can scale and ship on their own but cost you network\ncalls, harder debugging and more infrastructure. A good answer: start with a\nwell-structured monolith, split when team size or scaling pain justifies it.",
      },
      {
        id: 'message-queues',
        question: "Message queues",
        answer: "A queue (SQS, RabbitMQ, Kafka) lets one service hand work to another\nasynchronously. It decouples services, absorbs traffic spikes and allows\nretries. Example: after signup, queue the welcome email instead of making the\nuser wait for it.",
      },
      {
        id: 'rate-limiting',
        question: "Rate limiting",
        answer: "Caps how many requests a client can make in a time window, against abuse and\noverload. Algorithms: fixed window, sliding window, token bucket (which\nallows short bursts). Exceeding it returns 429.",
      },
    ],
  },
  {
    id: 'engineering-practice',
    name: "Engineering practice",
    concepts: [
      {
        id: 'types-of-tests',
        question: "Types of tests",
        answer: "Unit tests check one function or component in isolation, fast and numerous.\nIntegration tests check pieces together, like a component with its hooks and\na mocked API. End-to-end tests (Playwright, Cypress) drive the real app in a\nbrowser, slow but closest to what users do. Testing Library's approach for\nfrontend: test what the user sees and does, not implementation details.",
      },
      {
        id: 'tdd',
        question: "TDD",
        answer: "Write a failing test, write the least code to pass it, refactor. Red, green,\nrefactor. An honest take is fine: it works well for logic-heavy code and bug\nfixes, less for exploratory UI work.",
      },
      {
        id: 'git-merge-vs-rebase',
        question: "Git merge vs rebase",
        answer: "Merge joins branches with a merge commit and keeps the real history. Rebase\nreplays your commits on top of the target for a linear history, but it\nrewrites commits, so never rebase a branch other people have pulled.",
      },
      {
        id: 'ci-cd',
        question: "CI/CD",
        answer: "Continuous integration runs build, lint and tests on every push so breakage\nshows up early. Continuous delivery or deployment releases passing changes to\nstaging or production automatically.",
      },
      {
        id: 'design-patterns-to-be-able-to-name',
        question: "Design patterns to be able to name",
        answer: "Singleton: one shared instance, like a logger. Often called an anti-pattern\nbecause it's global state in disguise.\n\nObserver or pub/sub: subscribers are notified when something changes.\naddEventListener and store subscriptions are examples.\n\nFactory: a function that creates objects so callers don't depend on the\nconcrete class.\n\nStrategy: swap an algorithm at runtime behind a common interface, like\ndifferent payment methods.\n\nDecorator: wrap something to add behavior without changing it. HOCs in React\nare this.\n\nModule: private state with a public API. ES modules today.",
      },
      {
        id: 'dry-kiss-yagni',
        question: "DRY, KISS, YAGNI",
        answer: "DRY: one source of truth for each piece of knowledge. KISS: keep it simple.\nYAGNI: don't build for needs you only imagine. Worth adding: DRY applied too\nearly produces the wrong abstraction, and a little duplication is cheaper than\nthat.",
      },
      {
        id: 'technical-debt',
        question: "Technical debt",
        answer: "Shortcuts that make future changes slower. Sometimes taking it on is the right\ncall to ship. What matters is that it's deliberate, tracked, and paid down\nonce it costs more than it saved.",
      },
    ],
  },
  {
    id: 'when-you-don-t-know',
    name: "When you don't know",
    concepts: [
      {
        id: 'when-you-don-t-know',
        question: "When you don't know",
        answer: "Say what you do know and reason out loud: \"I haven't used X directly, but I'd\nexpect it to work like Y, because...\". Interviewers score the reasoning. A\nbluffed definition falls apart at the first follow-up.",
      },
    ],
  },
  {
    id: 'ways-of-working',
    name: "Ways of working",
    concepts: [
      {
        id: 'what-is-scrum',
        question: "What is Scrum?",
        answer: "An agile framework that delivers work in fixed-length sprints, usually two\nweeks. Three roles: the product owner owns the backlog and its priority, the\nscrum master removes blockers and protects the process, the developers build\nit. The backlog is refined, a sprint is planned, work is done, then it is\ndemoed and reviewed in a retrospective. The point is a short feedback loop, so\nyou find out you built the wrong thing in two weeks rather than six months.",
      },
      {
        id: 'scrum-vs-kanban',
        question: "Scrum vs Kanban",
        answer: "Scrum works in timeboxed sprints with a fixed commitment and ceremonies around\nit. Kanban has no sprints: work flows continuously, you cap how many items can\nbe in progress at once, and you optimise for cycle time. Scrum suits work that\ncan be planned a sprint ahead. Kanban suits interrupt-driven work like support\nor platform teams, where committing two weeks out is a fiction. Plenty of teams\nrun a hybrid and call it Scrum.",
      },
      {
        id: 'the-scrum-ceremonies',
        question: "The Scrum ceremonies",
        answer: "Sprint planning picks what the team commits to. The daily standup is fifteen\nminutes to surface blockers, not a status report to a manager. The review or\ndemo shows working software to stakeholders. The retrospective looks at how the\nteam worked and picks one or two things to change. Backlog refinement keeps the\nnext sprint's work ready. If standup regularly runs long or feels like\nreporting upward, that is the usual smell.",
      },
      {
        id: 'story-points-and-estimation',
        question: "Story points and estimation",
        answer: "Points measure relative size and uncertainty, not hours. A team estimates\nagainst past work, and velocity, the points completed per sprint, is used to\nforecast. They are deliberately not hours so that estimates are not treated as\ncommitments and do not get compared between teams. The common failure is\nmanagement treating velocity as a productivity target, at which point the\nnumbers inflate and stop meaning anything.",
      },
      {
        id: 'definition-of-done',
        question: "Definition of done",
        answer: "The checklist a piece of work must meet before anyone calls it finished:\nreviewed, tested, documented, deployed behind a flag, whatever the team agreed.\nIt exists so \"done\" means the same thing to everyone and work does not come\nback a sprint later. Without one, half-finished work accumulates and the sprint\nboard lies.",
      },
      {
        id: 'agile-vs-waterfall',
        question: "Agile vs waterfall",
        answer: "Waterfall plans everything up front and moves through requirements, design,\nbuild and test in sequence. It works when requirements genuinely cannot change,\nas with regulated hardware. Agile accepts that you learn what to build by\nbuilding it, so it works in short cycles with feedback at the end of each. Most\nreal teams are somewhere in between, and \"we are agile\" often just means \"we do\nstandups\".",
      },
      {
        id: 'code-review',
        question: "Code review",
        answer: "Another engineer reads your change before it merges. The value is catching\ndesign problems and spreading knowledge, not typos, which a linter should be\ndoing. Keep pull requests small, because review quality falls off a cliff past\na few hundred lines. As the reviewer, separate what blocks the merge from what\nis a suggestion. As the author, do not take it personally.",
      },
      {
        id: 'trunk-based-development-vs-git-flow',
        question: "Trunk based development vs Git Flow",
        answer: "Trunk based means everyone merges small changes to main frequently, often daily,\nbehind feature flags, and main is always releasable. Git Flow keeps long-lived\ndevelop and release branches. Long branches mean painful merges and delayed\nintegration, which is exactly what continuous integration is supposed to\nprevent. Trunk based is the modern default; Git Flow still fits software with\nreal versioned releases.",
      },
      {
        id: 'feature-flags',
        question: "Feature flags",
        answer: "A switch that turns code paths on and off without deploying. It separates\ndeploying from releasing, so you can ship unfinished work to production safely,\nroll out to one percent of users, and turn something off without a rollback.\nThe cost is complexity: every flag is a branch in the code, and flags nobody\nremoves become permanent dead weight. Give each one an owner and a removal\ndate.",
      },
      {
        id: 'semantic-versioning',
        question: "Semantic versioning",
        answer: "MAJOR.MINOR.PATCH. Patch for a backwards compatible bug fix, minor for\nbackwards compatible new features, major for a breaking change. It lets\nconsumers know what upgrading costs them, which is what a caret range in\npackage.json relies on. The discipline that makes it work is being honest about\nwhat counts as breaking.",
      },
      {
        id: 'on-call-and-incident-response',
        question: "On-call and incident response",
        answer: "Someone is responsible for production out of hours. When something breaks:\nacknowledge, mitigate first and diagnose second, communicate while you work,\nthen write it up. Mitigation beats root causing during an incident, so roll\nback before you investigate. A blameless postmortem asks what about the system\nlet this happen, not who did it, because the alternative is people hiding\nproblems.",
      },
      {
        id: 'observability-logs-metrics-traces',
        question: "Observability: logs, metrics, traces",
        answer: "Three complementary signals. Logs are discrete events with detail, good for\n\"what exactly happened to this request\". Metrics are aggregated numbers over\ntime, good for \"is anything wrong right now\" and for alerts. Traces follow one\nrequest across services, good for \"which hop is slow\". Monitoring tells you a\nknown thing broke; observability is being able to ask a question you did not\nplan for.",
      },
      {
        id: 'sla-slo-and-sli',
        question: "SLA, SLO and SLI",
        answer: "An SLI is the measurement, such as the fraction of requests served under 300ms.\nAn SLO is the internal target for that measurement, say 99.9 percent. An SLA is\nthe contract with a customer and has financial consequences if you miss it, so\nit is always looser than the SLO. The gap between the SLO and 100 percent is\nthe error budget, and when it is spent you stop shipping features and fix\nreliability instead.",
      },
      {
        id: 'technical-documentation-and-adrs',
        question: "Technical documentation and ADRs",
        answer: "An architecture decision record captures one decision: the context, the options\nconsidered, what was chosen and the consequences. It is short and it is never\nedited, only superseded by a later one. The value is six months on when someone\nasks why the system works this way, and the answer is written down rather than\nlost with whoever left. README for how to run it, ADRs for why it is like this.",
      },
      {
        id: 'estimation-and-why-it-goes-wrong',
        question: "Estimation and why it goes wrong",
        answer: "Estimates are forecasts, not promises, and they are wrong because the unknown\nwork is the part you have not thought of yet. Break work down until each piece\nis small enough to reason about, estimate ranges rather than single numbers,\nand re-forecast as you learn. The useful question in an interview is not how\nyou estimate but what you do when you realise the estimate was wrong, and the\nanswer is tell someone immediately rather than absorbing it quietly.",
      },
    ],
  },
]

export function findConcept(id: string): { group: ConceptGroup; concept: Concept } | undefined {
  for (const group of conceptGroups) {
    const concept = group.concepts.find((c) => c.id === id)
    if (concept) return { group, concept }
  }
  return undefined
}
