/**
 * Questions and ids only. The answers live in concepts.ts, which is loaded
 * on demand, so the sidebar costs almost nothing.
 *
 * Generated by scripts/build-concepts.py. Edit the source, not this file.
 */

export type ConceptRef = { id: string; question: string }
export type ConceptGroupRef = { id: string; name: string; concepts: ConceptRef[] }

export const conceptIndex: ConceptGroupRef[] = [
  {
    id: 'oop',
    name: "OOP",
    concepts: [
      { id: 'what-is-oop', question: "What is OOP?" },
      { id: 'the-four-pillars', question: "The four pillars" },
      { id: 'class-vs-object', question: "Class vs object" },
      { id: 'composition-vs-inheritance', question: "Composition vs inheritance" },
      { id: 'interface-vs-abstract-class', question: "Interface vs abstract class" },
      { id: 'overloading-vs-overriding', question: "Overloading vs overriding" },
      { id: 'is-javascript-object-oriented', question: "Is JavaScript object-oriented?" },
      { id: 'solid', question: "SOLID" },
      { id: 'static-members', question: "Static members" },
      { id: 'access-modifiers', question: "Access modifiers" },
    ],
  },
  {
    id: 'functional-programming',
    name: "Functional programming",
    concepts: [
      { id: 'what-is-functional-programming', question: "What is functional programming?" },
      { id: 'pure-function', question: "Pure function" },
      { id: 'immutability', question: "Immutability" },
      { id: 'higher-order-functions-and-currying', question: "Higher-order functions and currying" },
      { id: 'oop-vs-fp', question: "OOP vs FP" },
    ],
  },
  {
    id: 'javascript-and-typescript',
    name: "JavaScript and TypeScript",
    concepts: [
      { id: 'var-vs-let-vs-const', question: "var vs let vs const" },
      { id: 'hoisting', question: "Hoisting" },
      { id: 'closures', question: "Closures" },
      { id: 'how-does-this-work', question: "How does `this` work?" },
      { id: 'event-loop', question: "Event loop" },
      { id: 'promises-vs-async-await', question: "Promises vs async/await" },
      { id: 'equality-vs-strict-equality', question: "== vs ===" },
      { id: 'null-vs-undefined', question: "null vs undefined" },
      { id: 'prototypal-inheritance', question: "Prototypal inheritance" },
      { id: 'shallow-vs-deep-copy', question: "Shallow vs deep copy" },
      { id: 'debounce-vs-throttle', question: "Debounce vs throttle" },
      { id: 'bubbling-capturing-delegation', question: "Bubbling, capturing, delegation" },
      { id: 'typescript-interface-vs-type', question: "TypeScript: interface vs type" },
      { id: 'any-vs-unknown-vs-never', question: "any vs unknown vs never" },
      { id: 'generics', question: "Generics" },
    ],
  },
  {
    id: 'react',
    name: "React",
    concepts: [
      { id: 'virtual-dom-and-reconciliation', question: "Virtual DOM and reconciliation" },
      { id: 'why-do-keys-matter', question: "Why do keys matter?" },
      { id: 'state-vs-props', question: "State vs props" },
      { id: 'when-does-a-component-re-render', question: "When does a component re-render?" },
      { id: 'useeffect', question: "useEffect" },
      { id: 'usememo-usecallback-react-memo', question: "useMemo, useCallback, React.memo" },
      { id: 'controlled-vs-uncontrolled-inputs', question: "Controlled vs uncontrolled inputs" },
      { id: 'context-vs-a-state-library', question: "Context vs a state library" },
      { id: 'are-state-updates-synchronous', question: "Are state updates synchronous?" },
      { id: 'custom-hooks-and-rules-of-hooks', question: "Custom hooks and rules of hooks" },
      { id: 'csr-vs-ssr-vs-ssg-and-hydration', question: "CSR vs SSR vs SSG, and hydration" },
      { id: 'server-components', question: "Server Components" },
      { id: 'error-boundaries', question: "Error boundaries" },
    ],
  },
  {
    id: 'web-and-browser',
    name: "Web and browser",
    concepts: [
      { id: 'what-happens-when-you-type-a-url-and-press-enter', question: "What happens when you type a URL and press Enter?" },
      { id: 'http-methods-and-idempotency', question: "HTTP methods and idempotency" },
      { id: 'status-codes', question: "Status codes" },
      { id: 'rest-vs-graphql', question: "REST vs GraphQL" },
      { id: 'cookies-vs-localstorage-vs-sessionstorage', question: "Cookies vs localStorage vs sessionStorage" },
      { id: 'cors', question: "CORS" },
      { id: 'xss-and-csrf', question: "XSS and CSRF" },
      { id: 'authentication-vs-authorization-sessions-vs-jwt', question: "Authentication vs authorization, sessions vs JWT" },
      { id: 'reflow-vs-repaint', question: "Reflow vs repaint" },
      { id: 'core-web-vitals', question: "Core Web Vitals" },
      { id: 'http-caching', question: "HTTP caching" },
      { id: 'polling-vs-sse-vs-websockets', question: "Polling vs SSE vs WebSockets" },
      { id: 'http-2-and-http-3', question: "HTTP/2 and HTTP/3" },
      { id: 'accessibility-basics', question: "Accessibility basics" },
    ],
  },
  {
    id: 'cs-fundamentals',
    name: "CS fundamentals",
    concepts: [
      { id: 'big-o', question: "Big O" },
      { id: 'array-vs-linked-list', question: "Array vs linked list" },
      { id: 'how-does-a-hash-map-work', question: "How does a hash map work?" },
      { id: 'stack-vs-queue', question: "Stack vs queue" },
      { id: 'trees-graphs-bfs-vs-dfs', question: "Trees, graphs, BFS vs DFS" },
      { id: 'recursion', question: "Recursion" },
      { id: 'process-vs-thread', question: "Process vs thread" },
      { id: 'concurrency-vs-parallelism', question: "Concurrency vs parallelism" },
      { id: 'race-conditions-and-deadlocks', question: "Race conditions and deadlocks" },
    ],
  },
  {
    id: 'databases',
    name: "Databases",
    concepts: [
      { id: 'sql-vs-nosql', question: "SQL vs NoSQL" },
      { id: 'indexes', question: "Indexes" },
      { id: 'acid', question: "ACID" },
      { id: 'normalization-vs-denormalization', question: "Normalization vs denormalization" },
      { id: 'joins', question: "Joins" },
      { id: 'the-n-1-query-problem', question: "The N+1 query problem" },
    ],
  },
  {
    id: 'system-design-concepts',
    name: "System design concepts",
    concepts: [
      { id: 'vertical-vs-horizontal-scaling', question: "Vertical vs horizontal scaling" },
      { id: 'load-balancer', question: "Load balancer" },
      { id: 'caching-and-invalidation', question: "Caching and invalidation" },
      { id: 'cdn', question: "CDN" },
      { id: 'cap-theorem', question: "CAP theorem" },
      { id: 'monolith-vs-microservices', question: "Monolith vs microservices" },
      { id: 'message-queues', question: "Message queues" },
      { id: 'rate-limiting', question: "Rate limiting" },
    ],
  },
  {
    id: 'engineering-practice',
    name: "Engineering practice",
    concepts: [
      { id: 'types-of-tests', question: "Types of tests" },
      { id: 'tdd', question: "TDD" },
      { id: 'git-merge-vs-rebase', question: "Git merge vs rebase" },
      { id: 'ci-cd', question: "CI/CD" },
      { id: 'design-patterns-to-be-able-to-name', question: "Design patterns to be able to name" },
      { id: 'dry-kiss-yagni', question: "DRY, KISS, YAGNI" },
      { id: 'technical-debt', question: "Technical debt" },
    ],
  },
  {
    id: 'when-you-don-t-know',
    name: "When you don't know",
    concepts: [
      { id: 'when-you-don-t-know', question: "When you don't know" },
    ],
  },
]
