/**
 * Where to go once the walkthrough has landed.
 *
 * Hand-written: which problems drill which pattern, and why a pairing is worth
 * making when it is not obvious. Titles and difficulty are not here, because
 * remembering those is exactly the sort of thing that goes stale. They live in
 * the generated `practiceMeta.ts`, and `scripts/check-practice.py` verifies
 * every slug below against leetcode.com, so a slug that does not exist or has
 * gone premium fails the check rather than shipping as a dead link.
 *
 * Grouping is by the pattern the problem actually drills, not by the chapter
 * any particular course files it under.
 */
export type Problem = {
  /** The leetcode.com/problems/ slug. Verified; see the note above. */
  slug: string
  /** Only when the pairing needs justifying, or the problem goes past the walkthrough. */
  note?: string
}

export const problemUrl = (slug: string) => `https://leetcode.com/problems/${slug}/`

export const practice: Record<string, Problem[]> = {
  'two-sum': [
    { slug: 'two-sum' },
    { slug: 'contains-duplicate' },
    { slug: 'contains-duplicate-ii', note: 'The map stores the index, not just the fact.' },
    { slug: 'valid-anagram', note: 'A counter is a hash map with a narrower job.' },
    { slug: 'longest-consecutive-sequence', note: 'Looks like sorting. It is a set and one check.' },
    { slug: 'first-missing-positive', note: 'The O(1) space answer is cyclic sort, not a map.' },
  ],
  'two-pointers': [
    { slug: 'valid-palindrome' },
    { slug: 'two-sum-ii-input-array-is-sorted' },
    { slug: 'remove-duplicates-from-sorted-array' },
    { slug: 'remove-duplicates-from-sorted-array-ii' },
    { slug: 'move-zeroes', note: 'Read pointer and write pointer, the other shape of two pointers.' },
    { slug: '3sum', note: 'Fix one element, then it is the pair problem again.' },
    { slug: 'container-with-most-water' },
    { slug: 'trapping-rain-water', note: 'Also solvable with a monotonic stack.' },
  ],
  'sliding-window': [
    { slug: 'longest-substring-without-repeating-characters' },
    { slug: 'minimum-size-subarray-sum' },
    { slug: 'longest-repeating-character-replacement' },
    { slug: 'permutation-in-string', note: 'Fixed-size window, which is the easier of the two shapes.' },
    { slug: 'number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold' },
    { slug: 'longest-turbulent-subarray' },
    { slug: 'minimum-window-substring', note: 'The canonical variable-size window.' },
    { slug: 'sliding-window-median', note: 'Window plus two heaps.' },
  ],
  'binary-search': [
    { slug: 'binary-search', note: 'The template, on its own, with nothing hidden.' },
    { slug: 'search-insert-position', note: 'Where lo lands on a miss is the whole point.' },
    { slug: 'first-bad-version' },
    { slug: 'find-first-and-last-position-of-element-in-sorted-array', note: 'Two searches with different tie-breaking.' },
    { slug: 'search-in-rotated-sorted-array' },
    { slug: 'find-minimum-in-rotated-sorted-array' },
    { slug: 'search-a-2d-matrix', note: 'Treat the grid as one sorted array by index arithmetic.' },
    { slug: 'median-of-two-sorted-arrays', note: 'Binary search on the partition, not on the values.' },
  ],
  'binary-search-answer': [
    { slug: 'koko-eating-bananas', note: 'Start here. The predicate is almost written for you.' },
    { slug: 'capacity-to-ship-packages-within-d-days', note: 'The walkthrough problem, verbatim.' },
    { slug: 'find-the-smallest-divisor-given-a-threshold' },
    { slug: 'minimum-number-of-days-to-make-m-bouquets' },
    { slug: 'magnetic-force-between-two-balls', note: 'Maximise the minimum, so the predicate flips the other way.' },
    { slug: 'split-array-largest-sum', note: 'Ship capacity wearing a different hat.' },
  ],
  'bfs-grid': [
    { slug: 'number-of-islands' },
    { slug: 'flood-fill', note: 'The gentlest one. Start here if grids are new.' },
    { slug: 'rotting-oranges', note: 'Multi-source BFS: seed the queue with every rotten cell at once.' },
    { slug: '01-matrix', note: 'Also multi-source, and the reason BFS beats per-cell search.' },
    { slug: 'binary-tree-level-order-traversal', note: 'The same queue, on a tree.' },
    { slug: 'word-ladder', note: 'The graph is implicit: words are nodes, one-letter edits are edges.' },
  ],
  'iterative-dfs': [
    { slug: 'binary-tree-inorder-traversal', note: 'The explicit-stack version is the follow-up to the recursive one.' },
    { slug: 'clone-graph', note: 'A map from old node to new is the whole trick.' },
    { slug: 'max-area-of-island' },
    { slug: 'surrounded-regions', note: 'Work inwards from the border rather than outwards from the middle.' },
    { slug: 'pacific-atlantic-water-flow', note: 'Two searches from the edges, then intersect.' },
  ],
  'backtracking-subsets': [
    { slug: 'subsets' },
    { slug: 'subsets-ii', note: 'Duplicates, so the skip condition is the whole problem.' },
    { slug: 'permutations' },
    { slug: 'permutations-ii' },
    { slug: 'combinations' },
    { slug: 'combination-sum' },
    { slug: 'letter-combinations-of-a-phone-number' },
    { slug: 'palindrome-partitioning' },
    { slug: 'n-queens', note: 'Where pruning stops being optional.' },
  ],
  recursion: [
    { slug: 'fibonacci-number', note: 'The shape, with nothing else in the way.' },
    { slug: 'powx-n', note: 'Halving the exponent, which is recursion doing real work.' },
    { slug: 'reverse-string', note: 'Two pointers, or recursion, and comparing them is the lesson.' },
    { slug: 'swap-nodes-in-pairs', note: 'Trusting the recursive call is the whole difficulty.' },
    { slug: 'merge-two-sorted-lists' },
  ],
  'inorder-traversal': [
    { slug: 'maximum-depth-of-binary-tree' },
    { slug: 'same-tree' },
    { slug: 'invert-binary-tree' },
    { slug: 'binary-tree-preorder-traversal' },
    { slug: 'binary-tree-postorder-traversal' },
    { slug: 'diameter-of-binary-tree', note: 'What a node returns is not what the answer needs. That gap is the point.' },
    { slug: 'validate-binary-search-tree', note: 'Inorder must come out strictly increasing.' },
    { slug: 'lowest-common-ancestor-of-a-binary-search-tree' },
    { slug: 'kth-smallest-element-in-a-bst', note: 'Inorder, stopped early.' },
    { slug: 'binary-search-tree-iterator', note: 'Inorder, paused halfway, held on an explicit stack.' },
    { slug: 'binary-tree-maximum-path-sum', note: 'The classic return-one-thing, record-another.' },
  ],
  'bst-delete': [
    { slug: 'search-in-a-binary-search-tree' },
    { slug: 'insert-into-a-binary-search-tree', note: 'The easy half. Insert always lands at a leaf.' },
    { slug: 'delete-node-in-a-bst', note: 'The walkthrough problem. The two-child case is the question.' },
    { slug: 'trim-a-binary-search-tree' },
    { slug: 'convert-sorted-array-to-binary-search-tree', note: 'Build instead of delete, and the midpoint is the root.' },
  ],
  'min-heap': [
    { slug: 'last-stone-weight', note: 'The gentlest heap problem there is.' },
    { slug: 'kth-largest-element-in-a-stream' },
    { slug: 'k-closest-points-to-origin' },
    { slug: 'task-scheduler', note: 'Greedy plus a heap, and the counting argument is the real answer.' },
    { slug: 'merge-k-sorted-lists', note: 'A heap of size k over the list heads.' },
    { slug: 'find-median-from-data-stream', note: 'Two heaps facing each other.' },
    { slug: 'ipo', note: 'A heap fed by a sorted scan.' },
  ],
  heapify: [
    { slug: 'kth-largest-element-in-an-array', note: 'Build once, pop k times, and compare that against sorting.' },
    { slug: 'top-k-frequent-elements', note: 'Count, then build a heap over the counts.' },
    { slug: 'sort-an-array', note: 'Heapsort starts with exactly this build step.' },
  ],
  'coin-change': [
    { slug: 'climbing-stairs', note: 'Start here. It is Fibonacci wearing a hat.' },
    { slug: 'min-cost-climbing-stairs' },
    { slug: 'house-robber' },
    { slug: 'house-robber-ii', note: 'The circle is handled by running the line version twice.' },
    { slug: 'coin-change' },
    { slug: 'coin-change-ii', note: 'Counting ways, not minimising. The loop order flips.' },
    { slug: 'longest-increasing-subsequence' },
    { slug: 'word-break' },
    { slug: 'decode-ways' },
    { slug: 'minimum-cost-for-tickets' },
    { slug: 'palindromic-substrings' },
    { slug: 'longest-palindromic-substring' },
  ],
  kadane: [
    { slug: 'maximum-subarray', note: 'The walkthrough problem.' },
    { slug: 'best-time-to-buy-and-sell-stock', note: 'The same one pass, tracking a minimum instead of a total.' },
    { slug: 'maximum-sum-circular-subarray', note: 'Run it twice: best subarray, and total minus worst subarray.' },
    { slug: 'maximum-product-subarray', note: 'Track the minimum too, because a negative can flip it.' },
    { slug: 'maximum-absolute-sum-of-any-subarray' },
  ],
  'knapsack-01': [
    { slug: 'partition-equal-subset-sum', note: 'Subset sum in disguise, and the gentlest way in.' },
    { slug: 'target-sum', note: 'Signs instead of take-or-leave, and it rearranges into the same thing.' },
    { slug: 'last-stone-weight-ii', note: 'Also a partition problem, despite the name.' },
    { slug: 'ones-and-zeroes', note: 'Knapsack with two capacities, so the table gains a dimension.' },
    { slug: 'combination-sum-iv', note: 'Unbounded and order-sensitive. Worth contrasting with this one.' },
    { slug: 'profitable-schemes', note: 'Two constraints and a counting objective.' },
  ],
  'edit-distance': [
    { slug: 'unique-paths', note: 'The gentlest grid DP there is.' },
    { slug: 'longest-common-subsequence' },
    { slug: 'edit-distance' },
    { slug: 'longest-palindromic-subsequence', note: 'LCS of the string and its reverse.' },
    { slug: 'interleaving-string' },
    { slug: 'distinct-subsequences' },
    { slug: 'regular-expression-matching', note: 'Worth doing slowly, twice.' },
    { slug: 'shortest-common-supersequence', note: 'LCS, then walk the table back.' },
  ],
  'merge-sort': [
    { slug: 'sort-an-array', note: 'Where you actually implement it. Quicksort times out on the adversarial case.' },
    { slug: 'merge-sorted-array', note: 'The merge step alone, done backwards to stay in place.' },
    { slug: 'merge-two-sorted-lists', note: 'The merge step, with pointers.' },
    { slug: 'merge-k-sorted-lists', note: 'Pairwise merging beats a linear sweep.' },
  ],
  'count-inversions': [
    { slug: 'count-of-smaller-numbers-after-self', note: 'Counting during the merge, which is the walkthrough.' },
    { slug: 'reverse-pairs', note: 'Same idea, different pair condition.' },
    { slug: 'global-and-local-inversions', note: 'The one where you should notice a counting argument beats the sort.' },
  ],
  'merge-intervals': [
    { slug: 'merge-intervals' },
    { slug: 'insert-interval' },
    { slug: 'meeting-rooms' },
    { slug: 'meeting-rooms-ii', note: 'A heap of end times, or a sorted sweep of start and end events.' },
    { slug: 'non-overlapping-intervals', note: 'Sort by end, not by start. Worth understanding why.' },
    { slug: 'my-calendar-i', note: 'The same question asked one booking at a time.' },
  ],
  'monotonic-stack': [
    { slug: 'valid-parentheses', note: 'A plain stack, and the right warm-up for one.' },
    { slug: 'daily-temperatures', note: 'The walkthrough problem.' },
    { slug: 'next-greater-element-i' },
    { slug: 'next-greater-element-ii', note: 'Circular, handled by walking the array twice.' },
    { slug: 'largest-rectangle-in-histogram', note: 'The problem this pattern exists for.' },
    { slug: 'queue-reconstruction-by-height', note: 'Sort, then insert. Height reasoning, not a stack.' },
  ],
  'min-stack': [
    { slug: 'min-stack', note: 'The walkthrough problem.' },
    { slug: 'implement-queue-using-stacks', note: 'Two stacks, and the amortised argument is the answer.' },
    { slug: 'implement-stack-using-queues' },
    { slug: 'design-a-stack-with-increment-operation', note: 'Lazy propagation on a stack.' },
  ],
  'reverse-linked-list': [
    { slug: 'reverse-linked-list' },
    { slug: 'reverse-linked-list-ii', note: 'The same flip, bounded, which is where the dummy head earns its keep.' },
    { slug: 'merge-two-sorted-lists' },
    { slug: 'remove-nth-node-from-end-of-list', note: 'A gap between two pointers, and a dummy head.' },
    { slug: 'add-two-numbers' },
    { slug: 'copy-list-with-random-pointer', note: 'A map from old to new, or the interleaving trick.' },
  ],
  'fast-slow-pointers': [
    { slug: 'middle-of-the-linked-list', note: 'Fast and slow, at its simplest.' },
    { slug: 'linked-list-cycle' },
    { slug: 'linked-list-cycle-ii', note: 'Finding where the cycle starts. The proof is the interesting part.' },
    { slug: 'happy-number', note: 'No list in sight, and it is still cycle detection.' },
    { slug: 'find-the-duplicate-number', note: 'The array is the linked list. This is the famous one.' },
    { slug: 'palindrome-linked-list', note: 'Find the middle, reverse half, compare.' },
    { slug: 'maximum-twin-sum-of-a-linked-list' },
    { slug: 'reorder-list' },
  ],
  'topological-sort': [
    { slug: 'course-schedule', note: 'Cycle detection, phrased as a yes or no.' },
    { slug: 'course-schedule-ii', note: 'The same thing, now return the order.' },
    { slug: 'course-schedule-iv' },
    { slug: 'minimum-height-trees', note: 'Peel leaves inwards. Kahn, pointed at a different question.' },
    { slug: 'alien-dictionary', note: 'Building the edge list is the whole problem.' },
    { slug: 'sort-items-by-groups-respecting-dependencies', note: 'A topological sort inside another one.' },
  ],
  'union-find': [
    { slug: 'number-of-connected-components-in-an-undirected-graph' },
    { slug: 'redundant-connection', note: 'The edge that fails to union is the cycle.' },
    { slug: 'accounts-merge' },
    { slug: 'number-of-islands', note: 'Worth doing both ways, then saying why BFS is simpler here.' },
    { slug: 'satisfiability-of-equality-equations', note: 'Union the equalities first, then check the inequalities.' },
    { slug: 'swim-in-rising-water', note: 'Add cells in height order and ask when the ends connect.' },
  ],
  kruskal: [
    { slug: 'min-cost-to-connect-all-points', note: 'Kruskal almost verbatim, with the distances computed rather than given.' },
    { slug: 'find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree', note: 'Run Kruskal repeatedly, forcing or banning one edge at a time.' },
  ],
  prim: [
    { slug: 'min-cost-to-connect-all-points', note: 'Dense by construction, since every pair of points is an edge. Prim wins here.' },
  ],
  trie: [
    { slug: 'implement-trie-prefix-tree' },
    { slug: 'design-add-and-search-words-data-structure', note: 'Wildcards, so the search branches.' },
    { slug: 'longest-common-prefix', note: 'Does not need a trie, and comparing the two answers is the lesson.' },
    { slug: 'word-search-ii', note: 'A trie walked by a backtracking search, which is why it is here.' },
    { slug: 'prefix-and-suffix-search' },
  ],
  dijkstra: [
    { slug: 'network-delay-time' },
    { slug: 'path-with-maximum-probability', note: 'Maximise a product instead of minimising a sum. Same algorithm.' },
    { slug: 'cheapest-flights-within-k-stops', note: 'The stop limit breaks plain Dijkstra. Bellman-Ford fits better.' },
    { slug: 'path-with-minimum-effort', note: 'Minimise the largest edge on the path rather than the total.' },
    { slug: 'swim-in-rising-water', note: 'The same minimise-the-maximum shape.' },
  ],
  'bit-manipulation': [
    { slug: 'single-number', note: 'The walkthrough problem.' },
    { slug: 'missing-number', note: 'XOR the indices against the values and everything cancels but one.' },
    { slug: 'find-the-difference' },
    { slug: 'single-number-ii', note: 'Three of each. XOR alone cannot do it, and seeing why is the point.' },
    { slug: 'single-number-iii', note: 'Two loners, separated by one bit where they differ.' },
  ],
  'count-bits': [
    { slug: 'number-of-1-bits', note: 'The walkthrough problem.' },
    { slug: 'counting-bits', note: 'For every number up to n, which wants DP rather than the trick.' },
    { slug: 'power-of-two', note: 'One line, once you have seen n & (n - 1).' },
    { slug: 'hamming-distance', note: 'XOR, then popcount.' },
    { slug: 'total-hamming-distance', note: 'Count per bit column instead of per pair.' },
  ],
  'prefix-sums': [
    { slug: 'range-sum-query-immutable' },
    { slug: 'find-pivot-index' },
    { slug: 'product-of-array-except-self', note: 'Prefix and suffix, multiplied instead of added.' },
    { slug: 'subarray-sum-equals-k', note: 'Prefix sums plus a hash map. The combination is the point.' },
    { slug: 'contiguous-array', note: 'Map zeros to -1 and it becomes the previous problem.' },
    { slug: 'range-sum-query-2d-immutable' },
  ],
  'segment-tree': [
    { slug: 'range-sum-query-mutable', note: 'The walkthrough problem. Updates are what break prefix sums.' },
    { slug: 'count-of-smaller-numbers-after-self', note: 'A BIT or segment tree over value ranges.' },
    { slug: 'longest-increasing-subsequence-ii', note: 'The same recurrence, made fast by a range-max query.' },
    { slug: 'my-calendar-i', note: 'The interval version of the same need.' },
  ],
  quickselect: [
    { slug: 'kth-largest-element-in-an-array', note: 'The walkthrough problem, and the one they ask.' },
    { slug: 'top-k-frequent-elements', note: 'Quickselect over counts beats the heap here.' },
    { slug: 'k-closest-points-to-origin' },
    { slug: 'find-k-closest-elements', note: 'Binary search beats both. Worth noticing.' },
    { slug: 'wiggle-sort-ii', note: 'Quickselect for the median, then interleave.' },
  ],
  'matrix-rotate': [
    { slug: 'rotate-image', note: 'The walkthrough problem: transpose, then reverse each row.' },
    { slug: 'spiral-matrix', note: 'Four boundaries, shrinking.' },
    { slug: 'set-matrix-zeroes', note: 'The O(1) space version uses the first row and column as its own notes.' },
    { slug: 'transpose-matrix' },
  ],
  'cyclic-sort': [
    { slug: 'missing-number' },
    { slug: 'find-all-numbers-disappeared-in-an-array', note: 'Same idea, and you can mark in place by negating.' },
    { slug: 'find-the-duplicate-number', note: 'Also solvable as cycle detection, which is the famous answer.' },
    { slug: 'first-missing-positive', note: 'The purest version of the 1 to n tell.' },
  ],
  'reservoir-sampling': [
    { slug: 'linked-list-random-node', note: 'The walkthrough, with a list instead of a stream.' },
    { slug: 'random-pick-index', note: 'Reservoir of size one, per value.' },
    { slug: 'random-pick-with-blacklist', note: 'Not reservoir. Remapping, and comparing the two is worthwhile.' },
  ],
  'lru-cache': [
    { slug: 'lru-cache', note: 'The walkthrough problem.' },
    { slug: 'design-linked-list', note: 'The doubly linked half, on its own.' },
    { slug: 'lfu-cache', note: 'Frequency instead of recency, which needs a third structure.' },
    { slug: 'all-oone-data-structure', note: 'The same map-plus-list idea, pushed further.' },
  ],
  'jump-game': [
    { slug: 'jump-game' },
    { slug: 'jump-game-ii', note: 'Now count the jumps, which is a window over the reachable range.' },
    { slug: 'best-time-to-buy-and-sell-stock', note: 'One pass, tracking the minimum seen so far.' },
    { slug: 'gas-station', note: 'The invariant that makes greedy safe is the whole answer.' },
    { slug: 'partition-labels' },
  ],
  sieve: [
    { slug: 'count-primes', note: 'The walkthrough problem.' },
    { slug: 'ugly-number-ii', note: 'Not a sieve, and thinking it is costs you the O(n) answer.' },
    { slug: 'perfect-squares', note: 'DP over a precomputed set, which is the sieve mindset.' },
  ],
  'group-anagrams': [
    { slug: 'valid-anagram' },
    { slug: 'group-anagrams', note: 'The walkthrough problem.' },
    { slug: 'find-all-anagrams-in-a-string', note: 'A sliding window over a count signature.' },
    { slug: 'isomorphic-strings', note: 'A different canonical form for the same style of question.' },
  ],
  kmp: [
    { slug: 'find-the-index-of-the-first-occurrence-in-a-string', note: 'Where KMP belongs, though the naive answer passes.' },
    { slug: 'repeated-substring-pattern', note: 'One lps lookup answers it, which is a good sign you understood the table.' },
    { slug: 'longest-happy-prefix', note: 'It is literally the last entry of the lps table.' },
    { slug: 'shortest-palindrome', note: 'Build the table over s plus reverse of s.' },
  ],
  'quick-sort': [
    { slug: 'sort-an-array', note: 'Naive pivot choice times out here, which is the lesson.' },
    { slug: 'sort-colors', note: 'Dutch national flag: one pass, three regions, the partition idea distilled.' },
    { slug: 'kth-largest-element-in-an-array', note: 'Partition once and discard a side, which is quickselect.' },
  ],
  'insertion-sort': [
    { slug: 'insertion-sort-list', note: 'On a linked list, where there is no shifting to do.' },
    { slug: 'sort-an-array', note: 'It will time out, and knowing at what size is worth something.' },
  ],
  'selection-sort': [{ slug: 'sort-an-array', note: 'Only as a baseline to time the others against.' }],
  'bubble-sort': [{ slug: 'sort-an-array', note: 'Only as a baseline. It will time out.' }],
  'heap-sort': [
    { slug: 'sort-an-array', note: 'The one sort here with a guaranteed n log n worst case.' },
    { slug: 'kth-largest-element-in-an-array', note: 'Build a heap, pop k times.' },
  ],
  'counting-sort': [
    { slug: 'sort-colors', note: 'Three known values, so counting is the obvious answer before the one-pass one.' },
    { slug: 'height-checker', note: 'Small known range, and it is what the problem is built for.' },
    { slug: 'sort-array-by-increasing-frequency', note: 'Count, then sort the counts.' },
  ],
  'radix-sort': [
    { slug: 'maximum-gap', note: 'Built to make you reach for a non-comparison sort.' },
    { slug: 'sort-an-array', note: 'Integers with a bounded width, which is exactly its case.' },
  ],
  'bucket-sort': [
    { slug: 'top-k-frequent-elements', note: 'Bucket by frequency and the sort disappears entirely.' },
    { slug: 'sort-characters-by-frequency', note: 'Same idea, on characters.' },
    { slug: 'maximum-gap', note: 'Pigeonhole into buckets, then only compare across gaps.' },
  ],
}
