#!/usr/bin/env python3
"""Regenerates src/lib/concepts.ts from one or more markdown sources.

The source is not part of this repo. Point the script at it:

    python3 scripts/build-concepts.py a.md [b.md ...] [--skip "Section Name"]

Several sources are merged in order. Groups with the same name are combined.

Format: ## for a group heading, ### for a question, prose beneath it.
"""
import json
import pathlib
import re
import sys

OUT = pathlib.Path(__file__).parent.parent / 'src/lib/concepts.ts'

# Sections named with --skip are parsed and then dropped.
EXCLUDE_SECTIONS: set[str] = set()

# Headings that slugify to nothing useful.
SLUG_OVERRIDE = {
    '== vs ===': 'equality-vs-strict-equality',
}


def slug(s: str) -> str:
    out = re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')
    return out or 'untitled'


def parse(src: str):
    sections, cur_sec, cur_item = [], None, None

    def flush():
        nonlocal cur_item
        if cur_item and cur_sec is not None:
            body = '\n'.join(cur_item['body']).strip()
            if body:
                cur_sec['items'].append({'q': cur_item['q'], 'a': body})
        cur_item = None

    for ln in src.split('\n'):
        if ln.startswith('## '):
            flush()
            name = ln[3:].strip()
            cur_sec = {'name': name, 'items': []}
            if name not in EXCLUDE_SECTIONS:
                sections.append(cur_sec)
        elif ln.startswith('### '):
            flush()
            cur_item = {'q': ln[4:].strip(), 'body': []}
        elif cur_item is not None:
            cur_item['body'].append(ln)
        elif cur_sec is not None and ln.strip() and not ln.startswith('#'):
            cur_item = {'q': cur_sec['name'], 'body': [ln]}

    flush()
    return [s for s in sections if s['items']]


def main() -> int:
    args = sys.argv[1:]
    while '--skip' in args:
        i = args.index('--skip')
        EXCLUDE_SECTIONS.add(args[i + 1])
        del args[i : i + 2]

    if not args:
        print(__doc__, file=sys.stderr)
        return 2

    paths = [pathlib.Path(a) for a in args]
    missing = [p for p in paths if not p.exists()]
    if missing:
        for m in missing:
            print(f'source not found: {m}', file=sys.stderr)
        return 1

    sections: list[dict] = []
    for path in paths:
        for sec in parse(path.read_text()):
            existing = next((s for s in sections if s['name'] == sec['name']), None)
            if existing:
                existing['items'].extend(sec['items'])
            else:
                sections.append(sec)

    lines = [
        '/**',
        ' * Concept questions, the "explain X" half of an interview loop.',
        ' * Each answer is sized for 30 to 60 seconds of talking.',
        ' *',
        ' * Generated by scripts/build-concepts.py. Edit the source, not this file.',
        ' */',
        '',
        'export type Concept = { id: string; question: string; answer: string }',
        'export type ConceptGroup = { id: string; name: string; concepts: Concept[] }',
        '',
        'export const conceptGroups: ConceptGroup[] = [',
    ]

    seen, total = set(), 0
    for sec in sections:
        lines += [f'  {{', f"    id: '{slug(sec['name'])}',", f'    name: {json.dumps(sec["name"])},', '    concepts: [']
        for it in sec['items']:
            cid = SLUG_OVERRIDE.get(it['q'], slug(it['q'])[:48])
            base, n = cid, 2
            while cid in seen:
                cid, n = f'{base}-{n}', n + 1
            seen.add(cid)
            total += 1
            lines += [
                '      {',
                f"        id: '{cid}',",
                f'        question: {json.dumps(it["q"])},',
                f'        answer: {json.dumps(it["a"])},',
                '      },',
            ]
        lines += ['    ],', '  },']

    lines += [
        ']',
        '',
        'export function findConcept(id: string): { group: ConceptGroup; concept: Concept } | undefined {',
        '  for (const group of conceptGroups) {',
        '    const concept = group.concepts.find((c) => c.id === id)',
        '    if (concept) return { group, concept }',
        '  }',
        '  return undefined',
        '}',
        '',
    ]

    OUT.write_text('\n'.join(lines))

    print(f'{len(sections)} groups, {total} concepts -> {OUT.name}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
