/**
 * Generates src/lib/labels.ts: the id-to-title map the sidebar needs.
 *
 * The sidebar has to name 207 items, and reaching into concepts, guides and
 * the algorithm registry to do it pulls all of them into the first chunk,
 * which is what made splitting pointless last time. A generated index solves
 * that, and the drift it used to risk is covered by smoke.ts, which fails if
 * any label here disagrees with the thing it names.
 */
import { writeFileSync } from 'node:fs'
import { algorithms } from '../src/algorithms'
import { conceptGroups } from '../src/lib/concepts'
import { guideGroups } from '../src/lib/guides'

const PAGES: Record<string, string> = {
  router: 'Which pattern is this?',
  board: 'The complexity board',
}

const labels: Record<string, string> = {}
for (const [id, title] of Object.entries(PAGES)) labels[`page:${id}`] = title
for (const a of algorithms) labels[`algo:${a.id}`] = a.name
for (const g of conceptGroups) for (const c of g.concepts) labels[`concept:${c.id}`] = c.question
for (const g of guideGroups) for (const x of g.guides) labels[`guide:${x.id}`] = x.title

const body = Object.entries(labels)
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  .join('\n')

writeFileSync(
  new URL('../src/lib/labels.ts', import.meta.url),
  `/**\n * Generated by scripts/build-labels.ts. Do not edit.\n *\n * Exists so the sidebar can name everything without importing everything.\n * smoke.ts fails if any label disagrees with the item it names.\n */\nexport const labels: Record<string, string> = {\n${body}\n}\n`,
)
console.log(`wrote ${Object.keys(labels).length} labels`)

// Also emit a per-algorithm lazy registry. Hand-writing one is what sank the
// last attempt at splitting; deriving it from the same modules that define the
// algorithms means it cannot disagree with them.
import { readdirSync, readFileSync } from 'node:fs'

const dir = new URL('../src/algorithms/', import.meta.url)
const entries: [string, string, string][] = []
for (const file of readdirSync(dir).sort()) {
  if (!file.endsWith('.ts') || file === 'index.ts' || file === 'lazy.ts') continue
  const text = readFileSync(new URL(file, dir), 'utf8')
  const exported = text.match(/^export const (\w+): Algorithm = \{/m)
  const id = text.match(/^  id: '([^']+)',$/m)
  if (!exported || !id) throw new Error(`${file} does not export one Algorithm with an id`)
  entries.push([id[1], exported[1], file.replace(/\.ts$/, '')])
}
if (entries.length !== algorithms.length) {
  throw new Error(`found ${entries.length} algorithm modules but the registry has ${algorithms.length}`)
}

writeFileSync(
  new URL('../src/algorithms/lazy.ts', import.meta.url),
  `/**\n * Generated by scripts/build-labels.ts. Do not edit.\n *\n * One dynamic import per algorithm, so opening a walkthrough costs that\n * walkthrough rather than all ${entries.length} of them.\n */\nimport type { Algorithm } from '../engine/types'\n\nexport const lazyAlgorithms: Record<string, () => Promise<Algorithm>> = {\n` +
    entries.map(([id, name, mod]) => `  ${JSON.stringify(id)}: () => import('./${mod}').then((m) => m.${name}),`).join('\n') +
    `\n}\n`,
)
console.log(`wrote ${entries.length} lazy algorithm imports`)

// And a rough time per item, so the sidebar and the home page can say "4 min"
// instead of leaving you to guess whether this is a sip or a sitting. Frames
// for an algorithm, words for everything else; both are already sitting here.
const WORDS_PER_MINUTE = 130
const SECONDS_PER_FRAME = 8
const words = (s: string) => s.trim().split(/\s+/).filter(Boolean).length

const minutes: Record<string, number> = {}
for (const a of algorithms) {
  const input = Object.fromEntries(a.inputs.map((f) => [f.name, f.value]))
  let frames = 0
  for (const _ of a.run(input)) if (++frames > 5000) break
  minutes[`algo:${a.id}`] = Math.max(2, Math.round((frames * SECONDS_PER_FRAME) / 60))
}
for (const g of conceptGroups) {
  for (const c of g.concepts) {
    minutes[`concept:${c.id}`] = Math.max(1, Math.round(words(`${c.question} ${c.answer}`) / WORDS_PER_MINUTE))
  }
}
for (const g of guideGroups) {
  for (const x of g.guides) {
    const body = [x.blurb, ...x.sections.flatMap((s) => [s.heading, s.body ?? '', ...(s.items ?? [])])].join(' ')
    minutes[`guide:${x.id}`] = Math.max(1, Math.round(words(body) / WORDS_PER_MINUTE))
  }
}

writeFileSync(
  new URL('../src/lib/minutes.ts', import.meta.url),
  `/**\n * Generated by scripts/build-labels.ts. Do not edit.\n *\n * Roughly how long an item takes: ${SECONDS_PER_FRAME}s per frame for a walkthrough,\n * ${WORDS_PER_MINUTE} words a minute for everything else. Honest enough to plan a sitting\n * around, which is all it is for.\n */\nexport const minutes: Record<string, number> = {\n` +
    Object.entries(minutes)
      .map(([k, v]) => `  ${JSON.stringify(k)}: ${v},`)
      .join('\n') +
    `\n}\n`,
)
console.log(`wrote ${Object.keys(minutes).length} time estimates`)
