#!/usr/bin/env python3
"""Regenerates src/lib/concepts.ts and conceptIndex.ts from a markdown source.

The source is not part of this repo. Point the script at it:

    python3 scripts/build-concepts.py path/to/concepts.md [--skip "Section Name"]

Format: ## for a group heading, ### for a question, prose beneath it.
"""
import json
import pathlib
import re
import sys

OUT = pathlib.Path(__file__).parent.parent / 'src/lib/concepts.ts'
OUT_INDEX = pathlib.Path(__file__).parent.parent / 'src/lib/conceptIndex.ts'

# Sections named with --skip are parsed and then dropped.
EXCLUDE_SECTIONS: set[str] = set()

# Headings that slugify to nothing useful.
SLUG_OVERRIDE = {
    '== vs ===': 'equality-vs-strict-equality',
}


def slug(s: str) -> str:
    out = re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')
    return out or 'untitled'


def parse(src: str):
    sections, cur_sec, cur_item = [], None, None

    def flush():
        nonlocal cur_item
        if cur_item and cur_sec is not None:
            body = '\n'.join(cur_item['body']).strip()
            if body:
                cur_sec['items'].append({'q': cur_item['q'], 'a': body})
        cur_item = None

    for ln in src.split('\n'):
        if ln.startswith('## '):
            flush()
            name = ln[3:].strip()
            cur_sec = {'name': name, 'items': []}
            if name not in EXCLUDE_SECTIONS:
                sections.append(cur_sec)
        elif ln.startswith('### '):
            flush()
            cur_item = {'q': ln[4:].strip(), 'body': []}
        elif cur_item is not None:
            cur_item['body'].append(ln)
        elif cur_sec is not None and ln.strip() and not ln.startswith('#'):
            cur_item = {'q': cur_sec['name'], 'body': [ln]}

    flush()
    return [s for s in sections if s['items']]


def main() -> int:
    args = sys.argv[1:]
    while '--skip' in args:
        i = args.index('--skip')
        EXCLUDE_SECTIONS.add(args[i + 1])
        del args[i : i + 2]

    if not args:
        print(__doc__, file=sys.stderr)
        return 2

    src_path = pathlib.Path(args[0])
    if not src_path.exists():
        print(f'source not found: {src_path}', file=sys.stderr)
        return 1

    sections = parse(src_path.read_text())

    lines = [
        '/**',
        ' * Concept questions, the "explain X" half of an interview loop.',
        ' * Each answer is sized for 30 to 60 seconds of talking.',
        ' *',
        ' * Generated by scripts/build-concepts.py. Edit the source, not this file.',
        ' */',
        '',
        'export type Concept = { id: string; question: string; answer: string }',
        'export type ConceptGroup = { id: string; name: string; concepts: Concept[] }',
        '',
        'export const conceptGroups: ConceptGroup[] = [',
    ]

    seen, total = set(), 0
    for sec in sections:
        lines += [f'  {{', f"    id: '{slug(sec['name'])}',", f'    name: {json.dumps(sec["name"])},', '    concepts: [']
        for it in sec['items']:
            cid = SLUG_OVERRIDE.get(it['q'], slug(it['q'])[:48])
            base, n = cid, 2
            while cid in seen:
                cid, n = f'{base}-{n}', n + 1
            seen.add(cid)
            total += 1
            lines += [
                '      {',
                f"        id: '{cid}',",
                f'        question: {json.dumps(it["q"])},',
                f'        answer: {json.dumps(it["a"])},',
                '      },',
            ]
        lines += ['    ],', '  },']

    used = set()
    lines += [
        ']',
        '',
        'export function findConcept(id: string): { group: ConceptGroup; concept: Concept } | undefined {',
        '  for (const group of conceptGroups) {',
        '    const concept = group.concepts.find((c) => c.id === id)',
        '    if (concept) return { group, concept }',
        '  }',
        '  return undefined',
        '}',
        '',
    ]

    OUT.write_text('\n'.join(lines))

    # A light index for the sidebar: ids and questions only, no answers, so the
    # nav renders without pulling in the heavy chunk.
    idx = [
        '/**',
        ' * Questions and ids only. The answers live in concepts.ts, which is loaded',
        ' * on demand, so the sidebar costs almost nothing.',
        ' *',
        ' * Generated by scripts/build-concepts.py. Edit the source, not this file.',
        ' */',
        '',
        'export type ConceptRef = { id: string; question: string }',
        'export type ConceptGroupRef = { id: string; name: string; concepts: ConceptRef[] }',
        '',
        'export const conceptIndex: ConceptGroupRef[] = [',
    ]
    for sec in sections:
        idx += [
            '  {',
            f"    id: '{slug(sec['name'])}',",
            f'    name: {json.dumps(sec["name"])},',
            '    concepts: [',
        ]
        for it in sec['items']:
            cid = SLUG_OVERRIDE.get(it['q'], slug(it['q'])[:48])
            # Matches the dedup order used above.
            base, n = cid, 2
            while cid in used:
                cid, n = f'{base}-{n}', n + 1
            used.add(cid)
            idx.append(f"      {{ id: '{cid}', question: {json.dumps(it['q'])} }},")
        idx += ['    ],', '  },']
    idx += [']', '']
    OUT_INDEX.write_text('\n'.join(idx))

    print(f'{len(sections)} groups, {total} concepts')
    print(f'  -> {OUT.name} and {OUT_INDEX.name}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
