#!/usr/bin/env python3
"""Verifies every practice slug against leetcode.com and regenerates practiceMeta.ts.

    python3 scripts/check-practice.py [--write]

Without --write it only reports. With it, src/lib/practiceMeta.ts is rewritten
from the live problem list, so titles and difficulty are never remembered and
never go stale.

Exits non-zero if a slug does not exist, which is the failure worth catching:
a link that 404s is worse than a short list.
"""
import json
import pathlib
import re
import sys
import urllib.request

ROOT = pathlib.Path(__file__).parent.parent
SRC = ROOT / 'src/lib/practice.ts'
OUT = ROOT / 'src/lib/practiceMeta.ts'
API = 'https://leetcode.com/api/problems/all/'
LEVEL = {1: 'easy', 2: 'medium', 3: 'hard'}


def fetch() -> dict:
    req = urllib.request.Request(API, headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = json.load(r)
    out = {}
    for pair in data['stat_status_pairs']:
        s = pair['stat']
        out[s['question__title_slug']] = {
            'title': s['question__title'],
            'level': LEVEL[pair['difficulty']['level']],
            'paid': bool(pair['paid_only']),
        }
    return out


def main() -> int:
    slugs = re.findall(r"slug: '([^']+)'", SRC.read_text())
    known = fetch()
    print(f'{len(slugs)} entries, {len(set(slugs))} unique, checked against {len(known)} problems')

    missing = sorted({s for s in slugs if s not in known})
    for s in missing:
        print(f'  MISSING  {s} is not a leetcode slug')

    paid = sorted({s for s in slugs if s in known and known[s]['paid']})
    for s in paid:
        print(f'  premium  {s} needs a subscription')

    if '--write' in sys.argv:
        meta = {s: known[s] for s in sorted(set(slugs)) if s in known}
        body = ',\n'.join(
            f"  '{s}': {{ title: {json.dumps(v['title'])}, level: '{v['level']}'"
            + (', premium: true' if v['paid'] else '')
            + ' }'
            for s, v in meta.items()
        )
        OUT.write_text(
            '/**\n'
            ' * Generated by scripts/check-practice.py from the leetcode problem list.\n'
            ' * Do not edit. Titles and difficulty are facts, so they are fetched rather\n'
            ' * than remembered; `practice.ts` holds the part that is a judgement call.\n'
            ' */\n'
            "export type ProblemMeta = { title: string; level: 'easy' | 'medium' | 'hard'; premium?: boolean }\n\n"
            'export const problemMeta: Record<string, ProblemMeta> = {\n' + body + ',\n}\n'
        )
        print(f'  wrote {len(meta)} entries to {OUT.relative_to(ROOT)}')

    return 1 if missing else 0


if __name__ == '__main__':
    sys.exit(main())
